version: "3.8"
services:
  stocks-bot:
    restart: always
    image: dbeliakov/stocks-bot:latest
    container_name: stocks-bot
    env_file:
    - secrets.env
    expose:
    - 2112
    networks:
    - monitor-net

networks:
  monitor-net:
    external:
      name: dockprom_monitor-net
