name: Lint and Test Go code
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    name: Test and cover Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Install goveralls
        run: go get -u github.com/mattn/goveralls
      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
      - name: Submit coverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

